# Project information
site_name: Leetcode with Adam
site_author: Adam Zhang
site_description: >-
  A blog about DSA and Leetcode

theme:
  name: material
  # custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  # 定义两个颜色theme, 和toggle button
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: switch to dark mode
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: switch to light mode

plugins:
  - search
  
# markdown extensions        
markdown_extensions: 
  - pymdownx.arithmatex:
      generic: true 
  - admonition
  - pymdownx.superfences
  - pymdownx.details
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# page tree
nav:
  - Home: index.md
  - Algorithm:
    - algorithm/index.md
    - 1 Two Sum : algorithm/test.md
    - 2 Three Sum : algorithm/test2.md
  - leetcode:
    - leetcode/index.md
    - 1 two sum: leetcode/1-two-sum/README.md
    - 2 add two numbers: leetcode/2-add-two-numbers/README.md
    - 3 longest substring without repeating characters: leetcode/3-longest-substring-without-repeating-characters/README.md
    - 5 longest palindromic substring: leetcode/5-longest-palindromic-substring/README.md
    - 9 palindrome number: leetcode/9-palindrome-number/README.md
    - 13 roman to integer: leetcode/13-roman-to-integer/README.md
    - 14 longest common prefix: leetcode/14-longest-common-prefix/README.md
    - 19 remove nth node from end of list: leetcode/19-remove-nth-node-from-end-of-list/README.md
    - 20 valid parentheses: leetcode/20-valid-parentheses/README.md
    - 21 merge two sorted lists: leetcode/21-merge-two-sorted-lists/README.md
    - 24 swap nodes in pairs: leetcode/24-swap-nodes-in-pairs/README.md
    - 25 reverse nodes in k groups: leetcode/25-reverse-nodes-in-k-groups/README.md
    - 34 find first and last position of element in sorted array: leetcode/34-find-first-and-last-position-of-element-in-sorted-array/README.md
    - 35 search insert position: leetcode/35-search-insert-position/README.md
    - 46 permutations: leetcode/46-permutations/README.md
    - 53 maximum subarray: leetcode/53-maximum-subarray/README.md
    - 61 rotate list: leetcode/61-rotate-list/README.md
    - 62 unique paths: leetcode/62-unique-paths/README.md
    - 63 unique paths II: leetcode/63-unique-paths-II/README.md
    - 64 minimum path sum: leetcode/64-minimum-path-sum/README.md
    - 69 binary search: leetcode/69-binary-search/README.md
    - 70 climbing stairs: leetcode/70-climbing-stairs/README.md
    - 72 edit distance: leetcode/72-edit-distance/README.md
    - 77 combinations: leetcode/77-combinations/README.md
    - 78 subsets: leetcode/78-subsets/README.md
    - 79 word search: leetcode/79-word-search/README.md
    - 83 remove duplicates from sorted list: leetcode/83-remove-duplicates-from-sorted-list/README.md
    - 92 reverse linked list II: leetcode/92-reverse-linked-list-II/README.md
    - 94 binary tree inorder traversal: leetcode/94-binary-tree-inorder-traversal/README.md
    - 100 same tree: leetcode/100-same-tree/README.md
    - 101 symmetric tree: leetcode/101-symmetric-tree/README.md
    - 102 binary tree level order traversal: leetcode/102-binary-tree-level-order-traversal/README.md
    - 103 binary tree zigzag level order traversal: leetcode/103-binary-tree-zigzag-level-order-traversal/README.md
    - 104 maximum depth of binary tree: leetcode/104-maximum-depth-of-binary-tree/README.md
    - 107 binary tree level order traversal II: leetcode/107-binary-tree-level-order-traversal-II/README.md
    - 111 minimum depth of binary tree: leetcode/111-minimum-depth-of-binary-tree/README.md
    - 112 path sum: leetcode/112-path-sum/README.md
    - 113 path sum II: leetcode/113-path-sum-II/README.md
    - 118 pascal triangle: leetcode/118-pascal-triangle/README.md
    - 119 pascal triangle II: leetcode/119-pascal-triangle-II/README.md
    - 120 triangle: leetcode/120-triangle/README.md
    - 121 best time to buy and sell stock: leetcode/121-best-time-to-buy-and-sell-stock/README.md
    - 122 best time to buy and sell stock II: leetcode/122-best-time-to-buy-and-sell-stock-II/README.md
    - 125 valid palindrome: leetcode/125-valid-palindrome/README.md
    - 129 sum root to leaf numbers: leetcode/129-sum-root-to-leaf-numbers/README.md
    - 136 single number: leetcode/136-single-number/README.md
    - 141 linked list cycle: leetcode/141-linked-list-cycle/README.md
    - 142 linked list cycle II: leetcode/142-linked-list-cycle-II/README.md
    - 144 binary tree preorder traversal: leetcode/144-binary-tree-preorder-traversal/README.md
    - 145 binary tree postorder traversal: leetcode/145-binary-tree-postorder-traversal/README.md
    - 146 lru cache: leetcode/146-lru-cache/README.md
    - 152 maximum product subarray: leetcode/152-maximum-product-subarray/README.md
    - 160 intersection of two linked list: leetcode/160-intersection-of-two-linked-list/README.md
    - 161 one edit distance: leetcode/161-one-edit-distance/README.md
    - 167 two sum II input array is sorted: leetcode/167-two-sum-II-input-array-is-sorted/README.md
    - 169 majority element: leetcode/169-majority-element/README.md
    - 198 house robber: leetcode/198-house-robber/README.md
    - 202 happy number: leetcode/202-happy-number/README.md
    - 203 remove linked list elements: leetcode/203-remove-linked-list-elements/README.md
    - 205 isomorphic strings: leetcode/205-isomorphic-strings/README.md
    - 206 reverse linked list: leetcode/206-reverse-linked-list/README.md
    - 213 house robber II: leetcode/213-house-robber-II/README.md
    - 217 contains duplicate: leetcode/217-contains-duplicate/README.md
    - 221 maximum square: leetcode/221-maximum-square/README.md
    - 226 invert binary tree: leetcode/226-invert-binary-tree/README.md
    - 230 kth smallest element in BST: leetcode/230-kth-smallest-element-in-BST/README.md
    - 234 palindrome linked list: leetcode/234-palindrome-linked-list/README.md
    - 242 valid anagram: leetcode/242-valid-anagram/README.md
    - 243 shortest word distance: leetcode/243-shortest-word-distance/README.md
    - 252 meeting rooms: leetcode/252-meeting-rooms/README.md
    - 257 binary tree paths: leetcode/257-binary-tree-paths/README.md
    - 266 palindrome permutation: leetcode/266-palindrome-permutation/README.md
    - 278 first bad version: leetcode/278-first-bad-version/README.md
    - 283 Move Zeros: leetcode/283-Move-Zeros/README.md
    - 300 longest increasing subsequence: leetcode/300-longest-increasing-subsequence/README.md
    - 367 valid perfect square: leetcode/367-valid-perfect-square/README.md
    - 328 odd even linked list: leetcode/328-odd-even-linked-list/README.md
    - 344 reverse string: leetcode/344-reverse-string/README.md
    - 374 guess number higher or lower: leetcode/374-guess-number-higher-or-lower/README.md
    - 383 ransom note: leetcode/383-ransom-note/README.md
    - 387 first unique character in a string: leetcode/387-first-unique-character-in-a-string/README.md
    - 409 longest palindrome: leetcode/409-longest-palindrome/README.md
    - 412 fizz buzz: leetcode/412-fizz-buzz/README.md
    - 441 arranging coins: leetcode/441-arranging-coins/README.md
    - 442 find all duplicates in an array: leetcode/442-find-all-duplicates-in-an-array/README.md
    - 509 fibonacci number: leetcode/509-fibonacci-number/README.md
    - 530 minimum absolute difference in BST: leetcode/530-minimum-absolute-difference-in-BST/README.md
    - 560 subarray sum equals k: leetcode/560-subarray-sum-equals-k/README.md
    - 577 reverse words in a string III: leetcode/577-reverse-words-in-a-string-III/README.md
    - 617 merge two binary trees: leetcode/617-merge-two-binary-trees/README.md
    - 643 maximum average subarray I: leetcode/643-maximum-average-subarray-I/README.md
    - 653 two sum IV input is a BST: leetcode/653-two-sum-IV-input-is-a-BST/README.md
    - 673 number of longest increasing subsequence: leetcode/673-number-of-longest-increasing-subsequence/README.md
    - 680 valid palindrome: leetcode/680-valid-palindrome/README.md
    - 700 search in a binary search tree: leetcode/700-search-in-a-binary-search-tree/README.md
    - 704 binary search: leetcode/704-binary-search/README.md
    - 718 maximum length of repeated subarray: leetcode/718-maximum-length-of-repeated-subarray/README.md
    - 724 find pivot index: leetcode/724-find-pivot-index/README.md
    - 740 delete and earn: leetcode/740-delete-and-earn/README.md
    - 746 min cost climbing stairs: leetcode/746-min-cost-climbing-stairs/README.md
    - 783 minimum distance between BST nodes: leetcode/783-minimum-distance-between-BST-nodes/README.md
    - 873 length of longest fibonacci subsequence: leetcode/873-length-of-longest-fibonacci-subsequence/README.md
    - 876 middle of the linked list: leetcode/876-middle-of-the-linked-list/README.md
    - 918 maximum sum circular subarray: leetcode/918-maximum-sum-circular-subarray/README.md
    - 931 minimum falling path sum: leetcode/931-minimum-falling-path-sum/README.md
    - 938 range sum of BST: leetcode/938-range-sum-of-BST/README.md
    - 941 valid mountain array: leetcode/941-valid-mountain-array/README.md
    - 953 verifying an alien dictionary: leetcode/953-verifying-an-alien-dictionary/README.md
    - 978 longest turbulent subarray: leetcode/978-longest-turbulent-subarray/README.md
    - 983 minimum cost for tickets: leetcode/983-minimum-cost-for-tickets/README.md
    - 1014 best sightseeing pair: leetcode/1014-best-sightseeing-pair/README.md
    - 1025 divisor game: leetcode/1025-divisor-game/README.md
    - 1086 high five: leetcode/1086-high-five/README.md
    - 1108 defanging an ip address: leetcode/1108-defanging-an-ip-address/README.md
    - 1119 remove vowels from a string: leetcode/1119-remove-vowels-from-a-string/README.md
    - 1133 largest unique number: leetcode/1133-largest-unique-number/README.md
    - 1134 Armstrong: leetcode/1134-Armstrong/README.md
    - 1137 N th Tribonacci number: leetcode/1137-N-th-Tribonacci-number/README.md
    - 1143 longest common subsequence: leetcode/1143-longest-common-subsequence/README.md
    - 1150 check if a number is majority element in a sorted array: leetcode/1150-check-if-a-number-is-majority-element-in-a-sorted-array/README.md
    - 1165 single row keyboard: leetcode/1165-single-row-keyboard/README.md
    - 1180 count substrings with only one distinct letter: leetcode/1180-count-substrings-with-only-one-distinct-letter/README.md
    - 1186 maximum subarray sum with one deletion: leetcode/1186-maximum-subarray-sum-with-one-deletion/README.md
    - 1191 k concatenation maximum sum: leetcode/1191-k-concatenation-maximum-sum/README.md
    - 1196 how many apples can you put into the basket: leetcode/1196-how-many-apples-can-you-put-into-the-basket/README.md
    - 1213 intersection of three sorted array: leetcode/1213-intersection-of-three-sorted-array/README.md
    - 1290 convert binary number in a linked list to integer: leetcode/1290-convert-binary-number-in-a-linked-list-to-integer/README.md
    - 1305 all elements in two binary search trees: leetcode/1305-all-elements-in-two-binary-search-trees/README.md
    - 1385 find the distance value between two arrays: leetcode/1385-find-the-distance-value-between-two-arrays/README.md
    - 1474 delete N nodes after M nodes of a linked list: leetcode/1474-delete-N-nodes-after-M-nodes-of-a-linked-list/README.md
    - 1480 running sum of 1d array: leetcode/1480-running-sum-of-1d-array/README.md
    - 1567 maximum length of subarray with positive product: leetcode/1567-maximum-length-of-subarray-with-positive-product/README.md
    - 1876 substring of size three with distinct characters: leetcode/1876-substring-of-size-three-with-distinct-characters/README.md
    - 1971 find if path exists in graph: leetcode/1971-find-if-path-exists-in-graph/README.md
    - 2108 find the first palindromic string in the array: leetcode/2108-find-the-first-palindromic-string-in-the-array/README.md
    - 2130 maximum twin sum of a linked list: leetcode/2130-maximum-twin-sum-of-a-linked-list/README.md

      
  